name: deploy deployment
on:
  push:
    branches:
      - deployment

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: check out the code to build server
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }} 
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: prepare the docker-compose run
        run: |
              ls -1

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: webwebweb5/ghum-test-deploy-3:latest

      - name: prepare the docker-compose run
        run: |
              mkdir ghum-test-deploy-3-2
              cp docker-compose-deploy.yml ghum-test-deploy-3-2/docker-compose-deploy.yml 
              cd ghum-test-deploy-3-2 
              docker-compose -H ${{ secrets.HOST_SERVER }} down 
              docker-compose -H ${{ secrets.HOST_SERVER }} pull
              docker-compose -H ${{ secrets.HOST_SERVER }} up -d